package main.java.service.exception;

public class ArithmeticExeptionClass {
	
	public static int divide(int a , int b) {
		/*try {
		    return a/b;
		}
		catch(ArithmeticException e) {
			System.out.println("Exception thrown : "+e.getMessage());
			//throw e;
		}*/
		System.out.println("Hello");
		int res=a/b;
		//System.out.println("Hello");*/
		int[] arr=new int[0] ;
		System.out.println("printing val: "+arr[1]);
		return -1;
	}

}
